"""This module contains all the constant used by this script."""

INIT_CELL_COUNT = 1000
INIT_CELL_POSITION = 100.0
INIT_CELL_VELOCITY = 1.0
INIT_CELL_MASS = 1.0

CELL_MASS_LIMIT = 10.0

TARGET_ITERATIONS = 10000
